version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "8080:8080"
    user: vscode
    command: sleep infinity

